### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by iLPdev** [iLPdev/discMapper#93]
Related to open workflow issue, but maybe starting from a checklist like this nice one from Leris would be helpful for organizing releases now that they're going to become packages: https://wiki.mudlet.org/w/Release_Checklist

**Comment by iLPdev** [comment]
- [ ] merge outstanding approved pull requests
- [ ] create a new release/<version> branch off develop
- [ ] go through every single commit (in main repo) and ensure all new functionality is documented
- [ ] update any changes in built-in packages and scripts (generic_mapper, MDK, etc.)
- [ ] test package install on clean mudlet profile
- [ ] update readme/changelog
- [ ] close associated github issues and/or milestone
- [ ] merge release into main
- [ ] draft a proper github release on main
- [ ] add zipped .mpackage from src as asset to release
- [ ] publish release on main
- [ ] post update to thread on forums.mudlet.org
- [ ] post update to discord packages channel
- [ ] merge, don't squash or rebase, any bugfixes from the release branch into development (but don't delete, keep it around for a potential hotfix if needed)
